apiVersion: v1
kind: Service
metadata:
  name: todo-client-service
spec:
  selector:
    app: todo-client-app
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer