apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-server-app-deploy
spec:
  selector:
    matchLabels:
      app: todo-server-app
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-server-app
        tier: backend
        track: stable
    spec:
      containers:
      - image: todo-server-kubernetes-app:latest
        name: container1
        ports:
        - name: http
          containerPort: 5000
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: server-side-configs
        - secretRef:
            name: server-side-secrets
